"""
Policy & Intervention Simulation Module
─────────────────────────────────────────
Simulates the projected impact of five evidence-based public-health
interventions on overdose mortality using a compartmental + Monte Carlo
approach.

Interventions supported
───────────────────────
  naloxone_distribution   – increases naloxone accessibility → reduces fatal OD
  treatment_expansion     – expands MAT/MOUD capacity → reduces active users
  harm_reduction          – syringe programs, safe use sites → reduces OD rate
  law_enforcement         – drug seizures, arrests → short-term supply shock
  prevention_education    – school/community programs → long-term demand reduction

Model
─────
For each intervention, a logistic effect curve determines the monthly
reduction in overdose rate:

  effect(t) = efficacy_max / (1 + exp(-k * (t - inflection)))

Monte Carlo uncertainty bands are generated by sampling:
  - efficacy_max ~ N(μ, σ)
  - policy implementation lag ~ Uniform(lag_min, lag_max) months
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


# ── Intervention parameter library ───────────────────────────────────────────
@dataclass
class InterventionParams:
    name: str
    label: str
    description: str
    efficacy_max: float        # maximum % reduction in overdose rate (0–1)
    efficacy_std: float        # uncertainty in efficacy_max
    inflection_month: float    # month at which half of max effect is reached
    k: float                   # logistic growth rate
    lag_min: int               # minimum implementation lag (months)
    lag_max: int               # maximum implementation lag (months)
    cost_per_year_m: float     # estimated annual cost in $M
    evidence_level: str        # HIGH / MODERATE / LOW


INTERVENTION_LIBRARY: Dict[str, InterventionParams] = {
    "naloxone_distribution": InterventionParams(
        name="naloxone_distribution",
        label="Naloxone Distribution",
        description="Expand community naloxone access: pharmacies, first responders, vending machines.",
        efficacy_max=0.28,
        efficacy_std=0.06,
        inflection_month=4.0,
        k=0.5,
        lag_min=1, lag_max=3,
        cost_per_year_m=8.5,
        evidence_level="HIGH",
    ),
    "treatment_expansion": InterventionParams(
        name="treatment_expansion",
        label="Treatment Expansion (MAT/MOUD)",
        description="Increase access to medication-assisted treatment (buprenorphine, methadone).",
        efficacy_max=0.35,
        efficacy_std=0.08,
        inflection_month=8.0,
        k=0.35,
        lag_min=3, lag_max=9,
        cost_per_year_m=45.0,
        evidence_level="HIGH",
    ),
    "harm_reduction": InterventionParams(
        name="harm_reduction",
        label="Harm Reduction Programs",
        description="Syringe service programs, supervised consumption sites, fentanyl test strips.",
        efficacy_max=0.20,
        efficacy_std=0.07,
        inflection_month=6.0,
        k=0.40,
        lag_min=2, lag_max=6,
        cost_per_year_m=12.0,
        evidence_level="MODERATE",
    ),
    "law_enforcement": InterventionParams(
        name="law_enforcement",
        label="Law Enforcement (Supply Disruption)",
        description="Targeted drug trafficking interdiction and prosecution.",
        efficacy_max=0.12,
        efficacy_std=0.09,
        inflection_month=3.0,
        k=0.8,
        lag_min=1, lag_max=4,
        cost_per_year_m=30.0,
        evidence_level="LOW",
    ),
    "prevention_education": InterventionParams(
        name="prevention_education",
        label="Prevention & Education",
        description="School-based, community, and media prevention campaigns.",
        efficacy_max=0.10,
        efficacy_std=0.05,
        inflection_month=18.0,
        k=0.20,
        lag_min=6, lag_max=18,
        cost_per_year_m=5.0,
        evidence_level="MODERATE",
    ),
}


@dataclass
class SimulationResult:
    intervention: str
    baseline:     pd.DataFrame    # columns: month, overdose_rate
    scenario_mean: pd.DataFrame   # columns: month, overdose_rate
    scenario_lower: pd.DataFrame
    scenario_upper: pd.DataFrame
    lives_saved_mean: float
    lives_saved_lower: float
    lives_saved_upper: float
    cost_per_year_m: float
    evidence_level: str
    description: str


def _logistic_effect(t: np.ndarray, efficacy: float, k: float, inflection: float, lag: float) -> np.ndarray:
    """Logistic intervention effect curve with a lag offset."""
    t_adj = np.maximum(t - lag, 0.0)
    return efficacy / (1.0 + np.exp(-k * (t_adj - inflection)))


def run_simulation(
    baseline_rate: float,
    intervention_name: str,
    horizon: int = 24,
    n_monte_carlo: int = 500,
    population: float = 1_000_000,
    seed: int = 42,
) -> SimulationResult:
    """
    Runs a Monte Carlo policy simulation.

    Parameters
    ----------
    baseline_rate     : current overdose death rate per 100,000 population
    intervention_name : key from INTERVENTION_LIBRARY
    horizon           : simulation horizon in months
    n_monte_carlo     : number of MC samples for uncertainty bands
    population        : state/region population (used for lives-saved calculation)
    seed              : RNG seed for reproducibility

    Returns
    -------
    SimulationResult with mean + 90% CI trajectories
    """
    params = INTERVENTION_LIBRARY.get(intervention_name)
    if params is None:
        raise ValueError(f"Unknown intervention: {intervention_name}. "
                         f"Choose from {list(INTERVENTION_LIBRARY.keys())}")

    rng  = np.random.default_rng(seed)
    months = np.arange(horizon)

    # ── Baseline trend (slight upward drift + seasonal noise) ────────────────
    seasonal = 0.03 * np.sin(2 * np.pi * months / 12)
    drift    = 0.002 * months
    baseline_series = baseline_rate * (1 + drift + seasonal)

    # ── Monte Carlo samples ───────────────────────────────────────────────────
    all_trajectories = np.zeros((n_monte_carlo, horizon))
    for i in range(n_monte_carlo):
        eff   = rng.normal(params.efficacy_max, params.efficacy_std)
        eff   = np.clip(eff, 0.0, 0.65)
        lag   = float(rng.integers(params.lag_min, params.lag_max + 1))
        effect = _logistic_effect(months.astype(float), eff, params.k, params.inflection_month, lag)
        trajectory = baseline_series * (1.0 - effect)
        # Add small stochastic noise
        noise = rng.normal(0, baseline_rate * 0.03, horizon)
        all_trajectories[i] = np.maximum(trajectory + noise, 0.0)

    mean_traj  = all_trajectories.mean(axis=0)
    lower_traj = np.percentile(all_trajectories, 5, axis=0)
    upper_traj = np.percentile(all_trajectories, 95, axis=0)

    # ── Lives saved (per 100k population scale) ───────────────────────────────
    annual_scale = population / 100_000 / 12   # per-month scaling
    lives_mean  = float(np.sum(baseline_series - mean_traj)  * annual_scale)
    lives_lower = float(np.sum(baseline_series - upper_traj) * annual_scale)
    lives_upper = float(np.sum(baseline_series - lower_traj) * annual_scale)

    def _series_df(traj: np.ndarray) -> pd.DataFrame:
        return pd.DataFrame({"month": months.tolist(), "overdose_rate": np.round(traj, 3).tolist()})

    return SimulationResult(
        intervention=params.label,
        baseline=_series_df(baseline_series),
        scenario_mean=_series_df(mean_traj),
        scenario_lower=_series_df(lower_traj),
        scenario_upper=_series_df(upper_traj),
        lives_saved_mean=round(lives_mean, 1),
        lives_saved_lower=round(lives_lower, 1),
        lives_saved_upper=round(lives_upper, 1),
        cost_per_year_m=params.cost_per_year_m,
        evidence_level=params.evidence_level,
        description=params.description,
    )


def compare_interventions(
    baseline_rate: float,
    intervention_names: Optional[List[str]] = None,
    horizon: int = 24,
    population: float = 1_000_000,
) -> pd.DataFrame:
    """
    Runs all (or selected) interventions and returns a comparison DataFrame.

    Columns: intervention, lives_saved_mean, lives_saved_lower, lives_saved_upper,
             cost_per_year_m, evidence_level, cost_per_life_saved
    """
    names = intervention_names or list(INTERVENTION_LIBRARY.keys())
    rows = []
    for name in names:
        result = run_simulation(baseline_rate, name, horizon=horizon, population=population)
        lives = max(result.lives_saved_mean, 0.01)
        rows.append({
            "intervention":     result.intervention,
            "lives_saved_mean": result.lives_saved_mean,
            "lives_saved_lower": result.lives_saved_lower,
            "lives_saved_upper": result.lives_saved_upper,
            "cost_per_year_m":  result.cost_per_year_m,
            "evidence_level":   result.evidence_level,
            "cost_per_life_saved_k": round(result.cost_per_year_m * 1000 / lives, 1),
        })
    return pd.DataFrame(rows).sort_values("lives_saved_mean", ascending=False).reset_index(drop=True)
